Ex_4:Ex_4_main.o Ex_4.o
	gcc Ex_4_main.o Ex_4.o -o Ex_4
Ex_4.o:Ex_4.c Ex_4.h Ex_4_Types.h
	gcc -c Ex_4.c
Ex_4_main.o: Ex_4_main.c Ex_4.h Ex_4_Types.h
	gcc -c Ex_4_main.c
clean:
	rm Ex_4 Ex_4_main.o Ex_4.o
